openapi: 3.0.0
info:
  title: Hishana Consultancy API Swagger
  description: Hishana Consultancy API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://api.hishanaconsultancy.com/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Admin
  - name: Admin > Auth
  - name: Admin > Admin
  - name: Admin > Faq
  - name: Admin > Blogs
paths:
  /api/admin/login:
    post:
      tags:
        - Admin > Auth
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: info@hishanaconsultancy.com
                password:
                  type: string
                  example: Password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/logout:
    post:
      tags:
        - Admin > Auth
      summary: logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/me:
    get:
      tags:
        - Admin > Admin
      summary: show logged in admin data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faqs:
    post:
      tags:
        - Admin > Faq
      summary: store faq
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: hy
                answer:
                  type: string
                  example: hello
                order_no:
                  type: integer
                  example: '1'
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Faq
      summary: show all faqs
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faqs/{id}:
    post:
      tags:
        - Admin > Faq
      summary: update faq
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: hy
                answer:
                  type: string
                  example: hello
                order_no:
                  type: integer
                  example: '1'
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Faq
      summary: delete faq
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blogs:
    post:
      tags:
        - Admin > Blogs
      summary: store blog data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: etting Started with Laravel
                content:
                  type: string
                  example: Full blog content goes here...
                excerpt:
                  type: string
                  example: hy
                image:
                  type: string
                  format: binary
                is_featured:
                  type: integer
                  example: '1'
                status:
                  type: string
                  example: draft
                published_at:
                  type: string
                  example: '2026-05-01'
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Blogs
      summary: show all blogs
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '8'
        - name: search_keyword
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blogs/{id}:
    post:
      tags:
        - Admin > Blogs
      summary: update blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: etting Started with Laravel
                content:
                  type: string
                  example: Full blog content goes here...
                excerpt:
                  type: string
                  example: hy
                image:
                  type: string
                  format: binary
                is_featured:
                  type: integer
                  example: '1'
                status:
                  type: string
                  example: draft
                published_at:
                  type: string
                  example: '2026-05-01'
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Blogs
      summary: show single blog data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Blogs
      summary: delete blog
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
